# Kubernetes Deployment for myreactapp
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myreactapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myreactapp
  template:
    metadata:
      labels:
        app: myreactapp
    spec:
      containers:
      - name: myreactapp
        image: kneetrainer-app-client-dev:development
        ports:
        - containerPort: 3000

---
# Kubernetes Service for myreactapp
apiVersion: v1
kind: Service
metadata:
  name: myreactapp
spec:
  selector:
    app: myreactapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000