version: '3.4'

services:
  myexpressapp:
    container_name: kneeTrainerAPI
    restart: always
    image: kneetrainer-api-server-dev:development
    build:
      context: ./webIOTServerExpressJS/
      dockerfile: ./Dockerfile.dev
    stdin_open: true
    volumes:
      - ./webIOTServerExpressJS:/usr/src/api
      -  /usr/src/api/node_modules
      - ./database/:/usr/src/api/database/
    ports:
      - "5000:5000"
    networks:
      - webIOTtrainer

  myreactapp:
    container_name: kneeTrainerClient
    restart: always
    image: kneetrainer-app-client-dev:development
    build:
      context: ./webIOTReactFront/
      dockerfile: ./Dockerfile.dev
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - webIOTtrainer
    volumes:
      - ./webIOTReactFront:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - myexpressapp
  
  nginx:
    container_name: kneeTrainerNGINX
    build:
      context: ./nginx
      dockerfile: ./Dockerfile.dev
    ports: 
      - 7000:80
    restart: always
    networks:
      - webIOTtrainer
    depends_on:
      - myreactapp

networks:
  webIOTtrainer: