apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kneetrainer-app-ingress
  namespace: web-iot-trainer
spec:
  tls:
  - hosts:
    - kneetrainer.madarfamily.local
    secretName: kneetrainer-app-tls
  rules:
  - host: kneetrainer.madarfamily.local
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: kneetrainer-app-service
            port:
              number: 3000
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kneetrainer-app-certificate
  namespace: web-iot-trainer
spec:
  secretName: kneetrainer-app-tls
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  dnsNames:
  - kneetrainer.madarfamily.local