apiVersion: apps/v1
kind: Deployment
metadata:
  name: kneeTrainer-app-deployment
  namespace: web-iot-trainer
  labels:
    app: kneeTrainerAPP
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kneeTrainer-app
  template:
    metadata:
      labels:
        app: kneeTrainer-app
    spec:
      initContainers:
      - name: git-clone
        image: alpine/git
        command:
        - /bin/sh
        - -c
        - |
          git init &&
          git remote add -f origin https://github.com/almog2290/webIOTArgoCD.git &&
          git config core.sparseCheckout true &&
          echo 'dockers/webIOTReactFront/*' >> .git/info/sparse-checkout &&
          git pull origin main
        volumeMounts:
        - name: webIOTReactFront
          mountPath: /usr/src/app
      containers:
      - name: myreactapp
        image: madaralmog/kneetrainer-app-client-dev:1.0
        imagePullPolicy: ifNotPresent
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: webIOTReactFront
          mountPath: /usr/src/app
        - name: node_modules
          mountPath: /usr/src/app/node_modules
        - name: database
          mountPath: /usr/src/app/database
      restartPolicy: Always
      volumes:
      - name: webIOTReactFront
        persistentVolumeClaim:
          claimName: webIOTReactFront
---
apiVersion: v1
kind: Service
metadata:
  name: kneeTrainer-app-service
  namespace: web-iot-trainer
spec:
  selector:
    app: kneeTrainer-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP