apiVersion: apps/v1
kind: Deployment
metadata:
  name: kneetrainer-api-deployment
  namespace: web-iot-trainer
  labels:
    app: kneetrainer-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kneetrainer-api
  template:
    metadata:
      labels:
        app: kneetrainer-api
    spec:
      containers:
      - name: myexpressapp
        image: madaralmog/kneetrainer-api-server-dev:1.0
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: webiot-server-expressjs
          mountPath: /usr/src/api
        - name: database
          mountPath: /usr/src/api/database
      restartPolicy: Always
      volumes:
      - name: webiot-server-expressjs
        persistentVolumeClaim:
          claimName: webiot-server-expressjs
      - name: database
        persistentVolumeClaim:
          claimName: database
---
apiVersion: v1
kind: Service
metadata:
  name: kneetrainer-api-service
  namespace: web-iot-trainer
spec:
  selector:
    app: kneetrainer-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
