apiVersion: apps/v1
kind: Deployment
metadata:
  name: kneeTrainer-api-deployment
  namespace: web-iot-trainer
  labels:
    app: kneeTrainer-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kneeTrainer-api
  template:
    metadata:
      labels:
        app: kneeTrainer-api
    spec:
      initContainers:
      - name: git-clone
        image: alpine/git
        command:
        - /bin/sh
        - -c
        - |
          git init &&
          git remote add -f origin https://github.com/almog2290/webIOTArgoCD.git &&
          git config core.sparseCheckout true &&
          echo 'dockers/webIOTServerExpressJS/*' >> .git/info/sparse-checkout &&
          git pull origin main
        volumeMounts:
        - name: webIOTServerExpressJS
          mountPath: /usr/src/api
      - name: git-clone2
        image: alpine/git
        command:
        - /bin/sh
        - -c
        - |
          git init &&
          git remote add -f origin https://github.com/almog2290/webIOTArgoCD.git &&
          git config core.sparseCheckout true &&
          echo 'dockers/database/*' >> .git/info/sparse-checkout &&
          git pull origin main
        volumeMounts:
        - name: database
          mountPath: /usr/src/api/database
      containers:
      - name: myexpressapp
        image: madaralmog/kneetrainer-api-server-dev::1.0
        imagePullPolicy: ifNotPresent
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: webIOTServerExpressJS
          mountPath: /usr/src/api
        - name: database
          mountPath: /usr/src/api/database
      restartPolicy: Always
      volumes:
      - name: webIOTServerExpressJS
        persistentVolumeClaim:
          claimName: webIOTServerExpressJS
      - name: database
        persistentVolumeClaim:
          claimName: database
---
apiVersion: v1
kind: Service
metadata:
  name: kneeTrainer-api-service
  namespace: web-iot-trainer
spec:
  selector:
    app: kneeTrainerAPI
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
