# Kubernetes Deployment for myexpressapp
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myexpressapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myexpressapp
  template:
    metadata:
      labels:
        app: myexpressapp
    spec:
      containers:
      - name: myexpressapp
        image: /madaralmog/kneetrainer-api-server-dev:1.0
        ports:
        - containerPort: 5000
---
# Kubernetes Service for myexpressapp
apiVersion: v1
kind: Service
metadata:
  name: myexpressapp
spec:
  selector:
    app: myexpressapp
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      